export const FETCH_PET_DATA = 'FETCH_PET_DATA';
export const FETCH_PET_DATA_SUCCESS = 'FETCH_PET_DATA_SUCCESS';
export const FETCH_PET_DATA_ERROR = 'FETCH_PET_DATA_ERROR';

export const ADD_PET = 'ADD_PET';
export const UPDATE_PET = 'UPDATE_PET';
export const DELETE_PET = 'DELETE_PET';